### ISSUE TITLE
Show frequency distribution histogram and frequency metrics

### ISSUE THREAD

**Issue by christofferaakre** [christofferaakre/japanese-ebook-analysis#11]
As of https://github.com/christofferaakre/japanese-ebook-analysis/pull/10, we now have access
to frequency information from several different frequency lists, as well as an overall frequency that takes into account all the frequency lists. We can use this information to show histograms of the frequency distribution, and then we can also show some metrics regarding the frequency. However, I am not sure which metrics best sum up the overall frequency distribution.

**Comment by Tarran-Sidhaarth** [comment]
Hey could you assign this issue to me

**Comment by christofferaakre** [comment]
> Hey could you assign this issue to me

Sure!

**Comment by christofferaakre** [comment]
@Tarran-Sidhaarth I've assigned the issue to you. Let me know if you need any pointers on how the codebase functions!

**Comment by Tarran-Sidhaarth** [comment]
@christofferaakre hey thank you so much, this is my first contribution and I am a little confused about your code, could you let me know when you are free so that you could explain it to me.

**Comment by christofferaakre** [comment]
> @christofferaakre hey thank you so much, this is my first contribution and I am a little confused about your code, could you let me know when you are free so that you could explain it to me.

I am free now. Is there a specific thing you are confused about, or do you just want me to explain in general?

**Comment by Tarran-Sidhaarth** [comment]
could you explain in general

**Comment by Tarran-Sidhaarth** [comment]
how would you like to communicate?

**Comment by christofferaakre** [comment]
You can contact me on Discord (negosaki#4243) if you would rather talk there, and I'll post a summary here afterwards

**Comment by Tarran-Sidhaarth** [comment]
I have sent you a friend request, EpicnessX

**Comment by christofferaakre** [comment]
The relevant part of the code is the `analyse_ebook` functiond defined
in `book_utils.py`. The frequencies for the words and the other relevant data is stored int he `word_list` variable. You should use this data to make histograms and save them in the same folder as the other data is being saved, i.e. `book.book_dir`, preferably by defining a function to make the plots in either `book_utils.py` or `utils.py`, then calling that function in the `analyse_ebook` function, and then putting the url to the saved plot in the `book_data` object.
